version: '2'
services:
    api-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/api/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=api
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
